version: '3.7'
services:
  server:
    image: nginx
    init: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docs.template.conf:/etc/nginx/conf.d/default.conf
      - ../docs:/usr/share/nginx/html
    ports:
      - "3030:3030"
    environment:
      NGINX_PORT: 3030
